owner: elastic
repo: elastic-agent-changelog-tool
template:
  - asciidoc-embedded
  - markdown-breaking-template
  - markdown-deprecations-template
  - markdown-index-template
  - markdown-known-issues-template
components:
  - beats
  - elastic-agent
  - fleet-server
