# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
env:
  SLACK_CHANNEL: '#elastic-agent-control-plane'
  DOCKER_REGISTRY: 'docker.elastic.co'
steps:
  - label: ":buildkite: Build"
    command:
      - ".buildkite/scripts/build.sh"
    agents:
      image: golang:${GO_VERSION}
      cpu: "8"
      memory: "4G"

  - label: ":linux: Test on linux"
    key: test
    command:
      - ".buildkite/scripts/test.sh"
    agents:
      image: golang:${GO_VERSION}
      cpu: "8"
      memory: "4G"
    artifact_paths:
      - "junit-*.xml"

  - label: ":junit: Junit annotate"
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: "junit-*.xml"
          fail-build-on-error: true
    agents:
      provider: "gcp" #junit plugin requires docker
    depends_on:
      - step: "test"
        allow_failure: true

  - label: ":buildkite: Snapshot"
    key: snapshot
    command:
      - ".buildkite/scripts/snapshot.sh"
    agents:
      image: golang:${GO_VERSION}
      cpu: "8"
      memory: "4G"
    depends_on:
      - step: "test"
        allow_failure: false

  - label: ":buildkite: Release"
    key: release
    command:
      - ".buildkite/scripts/release.sh"
    agents:
      image: golang:${GO_VERSION}
      cpu: "8"
      memory: "4G"
    depends_on:
      - step: "test"
        allow_failure: false
