# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
env:
  GVM: 'v0.5.0'
  DOCKER_REGISTRY: 'docker.elastic.co'
steps:
  - label: ":buildkite: Build"
    command:
      - ".buildkite/scripts/build.sh"
    agents:
      image: golang:${GO_VERSION}
      cpu: "8"
      memory: "4G"

  - label: ":linux: Test on linux"
    key: test
    command:
      - ".buildkite/scripts/test.sh"
    agents:
      image: golang:${GO_VERSION}
      cpu: "8"
      memory: "4G"
    artifact_paths:
      - "tests-report.txt"

  - label: ":buildkite: Prepare reports"
    key: prepare-report
    command:
      - ".buildkite/scripts/prepare-report.sh"
    agents:
      image: golang:${GO_VERSION}
      cpu: "8"
      memory: "4G"
    artifact_paths:
      - "junit-*.xml"
    depends_on:
      - step: "test"
        allow_failure: true

  - label: ":junit: Junit annotate"
    agents:
      # requires at least "bash", "curl" and "git"
      image: "docker.elastic.co/ci-agent-images/buildkite-junit-annotate:1.0"
    plugins:
      - junit-annotate#v2.7.0:
          artifacts: "junit-*.xml"
          fail-build-on-error: true
          run-in-docker: false
    depends_on:
      - step: "prepare-report"
        allow_failure: true

  - label: ":buildkite: Snapshot"
    if: build.tag == null
    key: snapshot
    command:
      - ".buildkite/scripts/snapshot.sh"
    agents:
      provider: "gcp"
    depends_on:
      - step: "test"
        allow_failure: false

  - label: ":buildkite: Release"
    if: build.tag =~ /^v\d+\.\d+\.\d+.*$$/
    key: release
    command:
      - ".buildkite/scripts/release.sh"
    plugins:
      - elastic/vault-github-token#v0.1.0:
    agents:
      provider: "gcp"
    depends_on:
      - step: "test"
        allow_failure: false
