// begin {{.Version}} relnotes

[[release-notes-{{.Version}}]]
== {{.Component}} {{.Version}}

Review important information about the {{.Component}} {{.Version}} release.

{{ if .Security -}}
[discrete]
[[security-updates-{{.Version}}]]
=== Security updates

{{ range $k, $v := .Security }}
{{ $k }}::
{{ range $item := $v }}
* {{ $item.Summary | beautify }} {{ linkPRSource $item.Component $item.LinkedPR }} {{ linkIssueSource $item.Component $item.LinkedIssue }}
{{- end }}
{{- end }}
{{- end }}
{{ if .BreakingChange -}}
[discrete]
[[breaking-changes-{{.Version}}]]
=== Breaking changes

Breaking changes can prevent your application from optimal operation and
performance. Before you upgrade, review the breaking changes, then mitigate the
impact to your application.

// TODO: add details and impact
{{ range $k, $v := .BreakingChange }}
{{ $k }}::
{{ range $item := $v }}
* {{ $item.Summary | beautify }} {{ linkPRSource $item.Component $item.LinkedPR }} {{ linkIssueSource $item.Component $item.LinkedIssue }}
{{- end }}
{{- end }}
{{- end }}
{{ if .KnownIssue -}}
[discrete]
[[known-issues-{{.Version}}]]
=== Known issues

// TODO: add details and impact
{{ range $k, $v := .KnownIssue }}
{{ $k }}::
{{ range $item := $v }}
* {{ $item.Summary | beautify }} {{ linkPRSource $item.Component $item.LinkedPR }} {{ linkIssueSource $item.Component $item.LinkedIssue }}
{{- end }}
{{- end }}
{{- end }}
{{ if .Deprecation -}}
[discrete]
[[deprecations-{{.Version}}]]
=== Deprecations

The following functionality is deprecated in {{.Version}}, and will be removed in
{{.Version}}. Deprecated functionality does not have an immediate impact on your
application, but we strongly recommend you make the necessary updates after you
upgrade to {{.Version}}.

{{ range $k, $v := .Deprecation }}
{{ $k }}::
{{ range $item := $v }}
* {{ $item.Summary | beautify }} {{ linkPRSource $item.Component $item.LinkedPR }} {{ linkIssueSource $item.Component $item.LinkedIssue }}
{{- end }}
{{- end }}
{{- end }}
{{ if .Feature -}}
[discrete]
[[new-features-{{.Version}}]]
=== New features

The {{.Version}} release adds the following new and notable features.

{{ range $k, $v := .Feature }}
{{ $k }}::
{{ range $item := $v }}
* {{ $item.Summary | beautify }} {{ linkPRSource $item.Component $item.LinkedPR }} {{ linkIssueSource $item.Component $item.LinkedIssue }}
{{- end }}
{{- end }}
{{- end }}
{{ if .Enhancement }}
[discrete]
[[enhancements-{{.Version}}]]
=== Enhancements

{{ range $k, $v := .Enhancement }}
{{ $k }}::
{{ range $item := $v }}
* {{ $item.Summary | beautify }} {{ linkPRSource $item.Component $item.LinkedPR }} {{ linkIssueSource $item.Component $item.LinkedIssue }}
{{- end }}
{{- end }}
{{- end }}
{{ if .BugFix }}
[discrete]
[[bug-fixes-{{.Version}}]]
=== Bug fixes

{{ range $k, $v := .BugFix }}
{{ $k }}::
{{ range $item := $v }}
* {{ $item.Summary | beautify }} {{ linkPRSource $item.Component $item.LinkedPR }} {{ linkIssueSource $item.Component $item.LinkedIssue }}
{{- end }}
{{- end }}
{{- end }}

// end {{.Version}} relnotes