#!/bin/bash

set -euo pipefail

echo "Golang version:"
version=$(cat .go-version)
export GO_VERSION="${version}"
echo "${GO_VERSION}"

source .buildkite/scripts/tooling.sh

DOCKER_REGISTRY_SECRET_PATH="kv/ci-shared/platform-ingest/docker_registry_prod"
if [[ "$BUILDKITE_PIPELINE_SLUG" == "elastic-agent-changelog-tool" && "$BUILDKITE_STEP_KEY" == "snapshot" ]] || \
    [[ "$BUILDKITE_PIPELINE_SLUG" == "elastic-agent-changelog-tool" && "$BUILDKITE_STEP_KEY" == "release" ]]; then
    DOCKER_USERNAME_SECRET=$(retry 5 vault kv get -field user "${DOCKER_REGISTRY_SECRET_PATH}")
    DOCKER_PASSWORD_SECRET=$(retry 5 vault kv get -field password "${DOCKER_REGISTRY_SECRET_PATH}")
    docker login -u "${DOCKER_USERNAME_SECRET}" -p "${DOCKER_PASSWORD_SECRET}" "${DOCKER_REGISTRY}" 2>/dev/null
fi
